import React from 'react';

import './globals.css';
import NavHeader from '../components/navigatie/NavHeader';

import { AuthProvider } from '@/context/AuthProvider';

export const metadata = {
  title: 'FarmConnect',
  description: 'Generated by create next app',
};
/**
 * The root layout for all pages
 * @param{React.ReactNode} children
 * @constructor
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavHeader />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
