import React from 'react';

import './globals.css';
import NavHeader from '@/components/navigatie/NavHeader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
/**
 * The root layout for all pages
 * @param{React.ReactNode} children
 * @constructor
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavHeader />
        {children}
      </body>
    </html>
  );
}
