import React from 'react'
import './globals.css'
import NavHeader from "@/components/navigatie/NavHeader";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavHeader/>
      {children}
      </body>
    </html>
  )
}
